import { notFound } from "next/navigation"
import { getProject } from "@/app/actions/project-actions"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ProjectTasksList } from "@/components/project-tasks-list"
import { ProjectManagementActions } from "@/components/project-management-actions"
import { ProjectResourcesList } from "@/components/project-resources-list"
import { CalendarIcon, Clock, Code2, FileText } from "lucide-react"
import { formatDate } from "@/lib/utils"
import type { Database } from "@/types/supabase"

type Project = Database["public"]["Tables"]["projects"]["Row"]
type Resource = Database["public"]["Tables"]["resources"]["Row"]
type Task = Database["public"]["Tables"]["tasks"]["Row"]
type ProjectStatus = NonNullable<Project["status"]>

export default async function ProjectPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>
  searchParams: Promise<{ tab?: string }>
}) {
  const { id } = await params
  const { tab } = await searchParams
  const { project, tasks, resources } = await getProject(id)

  if (!project) {
    notFound()
  }

  const projectTyped: Project = project
  const taskList: Task[] = tasks ?? []
  const resourceList: Resource[] = resources ?? []

  const statusColors: Partial<Record<ProjectStatus, string>> = {
    Planning: "bg-blue-500",
    "In Progress": "bg-yellow-500",
    Completed: "bg-green-500",
    Cancelled: "bg-red-500",
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">{projectTyped.name}</h1>
          <div className="flex items-center gap-2 mt-2">
            <Badge variant="outline" className="text-sm">
              {projectTyped.project_type?.replace("-", " ").replace(/\b\w/g, (l: string) => l.toUpperCase())}
            </Badge>
            <Badge
              className={`${(projectTyped.status && statusColors[projectTyped.status]) || "bg-gray-500"} hover:${
                (projectTyped.status && statusColors[projectTyped.status]) || "bg-gray-600"
              }`}
            >
              {projectTyped.status}
            </Badge>
          </div>
        </div>
        <ProjectManagementActions project={projectTyped} />
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Project Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h3 className="font-medium flex items-center gap-2">
                <FileText className="h-4 w-4" /> Description
              </h3>
              <p className="text-sm text-muted-foreground mt-1">{projectTyped.description}</p>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <h3 className="font-medium flex items-center gap-2">
                  <CalendarIcon className="h-4 w-4" /> Due Date
                </h3>
                <p className="text-sm text-muted-foreground mt-1">
                  {projectTyped.due_date ? formatDate(projectTyped.due_date) : "Not set"}
                </p>
              </div>
              <div>
                <h3 className="font-medium flex items-center gap-2">
                  <Clock className="h-4 w-4" /> Estimated Time
                </h3>
                <p className="text-sm text-muted-foreground mt-1">{projectTyped.estimated_time || "Not estimated"}</p>
              </div>
            </div>
            <div>
              <h3 className="font-medium flex items-center gap-2">
                <Code2 className="h-4 w-4" /> Tech Stack
              </h3>
              <div className="flex flex-wrap gap-2 mt-1">
                {projectTyped.tech_stack?.map((tech, index) => (
                  <Badge key={index} variant="secondary">
                    {tech}
                  </Badge>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>AI Project Breakdown</CardTitle>
            <CardDescription>Generated by Groq AI</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground whitespace-pre-line">{projectTyped.ai_breakdown}</p>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue={tab === "resources" ? "resources" : "tasks"}>
        <TabsList>
          <TabsTrigger value="tasks">Tasks</TabsTrigger>
          <TabsTrigger value="resources">Resources</TabsTrigger>
        </TabsList>
        <TabsContent value="tasks" className="mt-4">
          <ProjectTasksList projectId={projectTyped.id} initialTasks={taskList} resources={resourceList} />
        </TabsContent>
        <TabsContent value="resources" className="mt-4">
          <ProjectResourcesList projectId={projectTyped.id} initialResources={resourceList} />
        </TabsContent>
      </Tabs>
    </div>
  )
}
